USE [BDENREL_QA]
GO

INSERT INTO dbo.CatTecnologias VALUES(1,'BIOTERMOELECTRICA BIOGAS','SNRBIOGBE001',1)
INSERT INTO dbo.CatTecnologias VALUES(2,'HIDROELECTRICA','SNRHIDROE001',1)
INSERT INTO dbo.CatTecnologias VALUES(3,'BIOTERMOELECTRICA FORESTAL','SNRBIOCRF001',1)
INSERT INTO dbo.CatTecnologias VALUES(4,'EOLOELECTRICA','SNREOLCON001',1)
INSERT INTO dbo.CatTecnologias VALUES(5,'GEOTERMOELECTRICA EXPLORACION','SNRGEOERN001',1)
INSERT INTO dbo.CatTecnologias VALUES(6,'SOLAR FOTOVOLTAICA','SNRSOLFOT001',1)
INSERT INTO dbo.CatTecnologias VALUES(7,'GEOTERMOELECTRICA EXPLOTACION','SNRGEOETN001',1)

