USE [master]

IF EXISTS(select * from sys.databases where name='BDENREL_QA')
BEGIN
	ALTER DATABASE BDENREL_QA SET SINGLE_USER WITH ROLLBACK IMMEDIATE
	DROP DATABASE BDENREL_QA
END

CREATE DATABASE BDENREL_QA
