//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENREL.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CatEmpresas", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CatEmpresas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int E_IdEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string E_NombreComercialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string E_RazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string E_RFCField;
        
        private int E_IdTipoVialidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string E_CalleField;
        
        private int E_NumeroExteriorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string E_NumeroInteriorField;
        
        private int E_IdTipoAsentamientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string E_ColoniaField;
        
        private int E_IdLocalidadField;
        
        private int E_IdMunicipioField;
        
        private int E_IdEntidadFederativaField;
        
        private System.Nullable<int> E_CodigoPostalField;
        
        private System.Nullable<int> E_LadaField;
        
        private int E_TelefonoFijoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string E_CorreoElectronicoField;
        
        private bool E_ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string E_LocalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string E_MunicipioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string E_EntidadFederativaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string E_ClavePrivadaField;
        
        private System.DateTime E_FechaInicioField;
        
        private System.DateTime E_FechaFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string E_TecnologiaField;
        
        private double E_MontoInversionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int E_IdEmpresa {
            get {
                return this.E_IdEmpresaField;
            }
            set {
                if ((this.E_IdEmpresaField.Equals(value) != true)) {
                    this.E_IdEmpresaField = value;
                    this.RaisePropertyChanged("E_IdEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string E_NombreComercial {
            get {
                return this.E_NombreComercialField;
            }
            set {
                if ((object.ReferenceEquals(this.E_NombreComercialField, value) != true)) {
                    this.E_NombreComercialField = value;
                    this.RaisePropertyChanged("E_NombreComercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string E_RazonSocial {
            get {
                return this.E_RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.E_RazonSocialField, value) != true)) {
                    this.E_RazonSocialField = value;
                    this.RaisePropertyChanged("E_RazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string E_RFC {
            get {
                return this.E_RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.E_RFCField, value) != true)) {
                    this.E_RFCField = value;
                    this.RaisePropertyChanged("E_RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int E_IdTipoVialidad {
            get {
                return this.E_IdTipoVialidadField;
            }
            set {
                if ((this.E_IdTipoVialidadField.Equals(value) != true)) {
                    this.E_IdTipoVialidadField = value;
                    this.RaisePropertyChanged("E_IdTipoVialidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string E_Calle {
            get {
                return this.E_CalleField;
            }
            set {
                if ((object.ReferenceEquals(this.E_CalleField, value) != true)) {
                    this.E_CalleField = value;
                    this.RaisePropertyChanged("E_Calle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int E_NumeroExterior {
            get {
                return this.E_NumeroExteriorField;
            }
            set {
                if ((this.E_NumeroExteriorField.Equals(value) != true)) {
                    this.E_NumeroExteriorField = value;
                    this.RaisePropertyChanged("E_NumeroExterior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string E_NumeroInterior {
            get {
                return this.E_NumeroInteriorField;
            }
            set {
                if ((object.ReferenceEquals(this.E_NumeroInteriorField, value) != true)) {
                    this.E_NumeroInteriorField = value;
                    this.RaisePropertyChanged("E_NumeroInterior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int E_IdTipoAsentamiento {
            get {
                return this.E_IdTipoAsentamientoField;
            }
            set {
                if ((this.E_IdTipoAsentamientoField.Equals(value) != true)) {
                    this.E_IdTipoAsentamientoField = value;
                    this.RaisePropertyChanged("E_IdTipoAsentamiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string E_Colonia {
            get {
                return this.E_ColoniaField;
            }
            set {
                if ((object.ReferenceEquals(this.E_ColoniaField, value) != true)) {
                    this.E_ColoniaField = value;
                    this.RaisePropertyChanged("E_Colonia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int E_IdLocalidad {
            get {
                return this.E_IdLocalidadField;
            }
            set {
                if ((this.E_IdLocalidadField.Equals(value) != true)) {
                    this.E_IdLocalidadField = value;
                    this.RaisePropertyChanged("E_IdLocalidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int E_IdMunicipio {
            get {
                return this.E_IdMunicipioField;
            }
            set {
                if ((this.E_IdMunicipioField.Equals(value) != true)) {
                    this.E_IdMunicipioField = value;
                    this.RaisePropertyChanged("E_IdMunicipio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int E_IdEntidadFederativa {
            get {
                return this.E_IdEntidadFederativaField;
            }
            set {
                if ((this.E_IdEntidadFederativaField.Equals(value) != true)) {
                    this.E_IdEntidadFederativaField = value;
                    this.RaisePropertyChanged("E_IdEntidadFederativa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public System.Nullable<int> E_CodigoPostal {
            get {
                return this.E_CodigoPostalField;
            }
            set {
                if ((this.E_CodigoPostalField.Equals(value) != true)) {
                    this.E_CodigoPostalField = value;
                    this.RaisePropertyChanged("E_CodigoPostal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public System.Nullable<int> E_Lada {
            get {
                return this.E_LadaField;
            }
            set {
                if ((this.E_LadaField.Equals(value) != true)) {
                    this.E_LadaField = value;
                    this.RaisePropertyChanged("E_Lada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public int E_TelefonoFijo {
            get {
                return this.E_TelefonoFijoField;
            }
            set {
                if ((this.E_TelefonoFijoField.Equals(value) != true)) {
                    this.E_TelefonoFijoField = value;
                    this.RaisePropertyChanged("E_TelefonoFijo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string E_CorreoElectronico {
            get {
                return this.E_CorreoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.E_CorreoElectronicoField, value) != true)) {
                    this.E_CorreoElectronicoField = value;
                    this.RaisePropertyChanged("E_CorreoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public bool E_Activo {
            get {
                return this.E_ActivoField;
            }
            set {
                if ((this.E_ActivoField.Equals(value) != true)) {
                    this.E_ActivoField = value;
                    this.RaisePropertyChanged("E_Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string E_Localidad {
            get {
                return this.E_LocalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.E_LocalidadField, value) != true)) {
                    this.E_LocalidadField = value;
                    this.RaisePropertyChanged("E_Localidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string E_Municipio {
            get {
                return this.E_MunicipioField;
            }
            set {
                if ((object.ReferenceEquals(this.E_MunicipioField, value) != true)) {
                    this.E_MunicipioField = value;
                    this.RaisePropertyChanged("E_Municipio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string E_EntidadFederativa {
            get {
                return this.E_EntidadFederativaField;
            }
            set {
                if ((object.ReferenceEquals(this.E_EntidadFederativaField, value) != true)) {
                    this.E_EntidadFederativaField = value;
                    this.RaisePropertyChanged("E_EntidadFederativa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string E_ClavePrivada {
            get {
                return this.E_ClavePrivadaField;
            }
            set {
                if ((object.ReferenceEquals(this.E_ClavePrivadaField, value) != true)) {
                    this.E_ClavePrivadaField = value;
                    this.RaisePropertyChanged("E_ClavePrivada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=22)]
        public System.DateTime E_FechaInicio {
            get {
                return this.E_FechaInicioField;
            }
            set {
                if ((this.E_FechaInicioField.Equals(value) != true)) {
                    this.E_FechaInicioField = value;
                    this.RaisePropertyChanged("E_FechaInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=23)]
        public System.DateTime E_FechaFin {
            get {
                return this.E_FechaFinField;
            }
            set {
                if ((this.E_FechaFinField.Equals(value) != true)) {
                    this.E_FechaFinField = value;
                    this.RaisePropertyChanged("E_FechaFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string E_Tecnologia {
            get {
                return this.E_TecnologiaField;
            }
            set {
                if ((object.ReferenceEquals(this.E_TecnologiaField, value) != true)) {
                    this.E_TecnologiaField = value;
                    this.RaisePropertyChanged("E_Tecnologia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=25)]
        public double E_MontoInversion {
            get {
                return this.E_MontoInversionField;
            }
            set {
                if ((this.E_MontoInversionField.Equals(value) != true)) {
                    this.E_MontoInversionField = value;
                    this.RaisePropertyChanged("E_MontoInversion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name GetSiteListCountResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSiteListCount", ReplyAction="*")]
        ENREL.ServiceReference1.GetSiteListCountResponse GetSiteListCount(ENREL.ServiceReference1.GetSiteListCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSiteListCount", ReplyAction="*")]
        System.Threading.Tasks.Task<ENREL.ServiceReference1.GetSiteListCountResponse> GetSiteListCountAsync(ENREL.ServiceReference1.GetSiteListCountRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/recibirTramite", ReplyAction="*")]
        ENREL.ServiceReference1.recibirTramiteResponse recibirTramite(ENREL.ServiceReference1.recibirTramiteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/recibirTramite", ReplyAction="*")]
        System.Threading.Tasks.Task<ENREL.ServiceReference1.recibirTramiteResponse> recibirTramiteAsync(ENREL.ServiceReference1.recibirTramiteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSiteListCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSiteListCount", Namespace="http://tempuri.org/", Order=0)]
        public ENREL.ServiceReference1.GetSiteListCountRequestBody Body;
        
        public GetSiteListCountRequest() {
        }
        
        public GetSiteListCountRequest(ENREL.ServiceReference1.GetSiteListCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetSiteListCountRequestBody {
        
        public GetSiteListCountRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSiteListCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSiteListCountResponse", Namespace="http://tempuri.org/", Order=0)]
        public ENREL.ServiceReference1.GetSiteListCountResponseBody Body;
        
        public GetSiteListCountResponse() {
        }
        
        public GetSiteListCountResponse(ENREL.ServiceReference1.GetSiteListCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSiteListCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSiteListCountResult;
        
        public GetSiteListCountResponseBody() {
        }
        
        public GetSiteListCountResponseBody(string GetSiteListCountResult) {
            this.GetSiteListCountResult = GetSiteListCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class recibirTramiteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="recibirTramite", Namespace="http://tempuri.org/", Order=0)]
        public ENREL.ServiceReference1.recibirTramiteRequestBody Body;
        
        public recibirTramiteRequest() {
        }
        
        public recibirTramiteRequest(ENREL.ServiceReference1.recibirTramiteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class recibirTramiteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ENREL.ServiceReference1.CatEmpresas empresa;
        
        public recibirTramiteRequestBody() {
        }
        
        public recibirTramiteRequestBody(string id, ENREL.ServiceReference1.CatEmpresas empresa) {
            this.id = id;
            this.empresa = empresa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class recibirTramiteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="recibirTramiteResponse", Namespace="http://tempuri.org/", Order=0)]
        public ENREL.ServiceReference1.recibirTramiteResponseBody Body;
        
        public recibirTramiteResponse() {
        }
        
        public recibirTramiteResponse(ENREL.ServiceReference1.recibirTramiteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class recibirTramiteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool recibirTramiteResult;
        
        public recibirTramiteResponseBody() {
        }
        
        public recibirTramiteResponseBody(bool recibirTramiteResult) {
            this.recibirTramiteResult = recibirTramiteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ENREL.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ENREL.ServiceReference1.WebService1Soap>, ENREL.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ENREL.ServiceReference1.GetSiteListCountResponse ENREL.ServiceReference1.WebService1Soap.GetSiteListCount(ENREL.ServiceReference1.GetSiteListCountRequest request) {
            return base.Channel.GetSiteListCount(request);
        }
        
        public string GetSiteListCount() {
            ENREL.ServiceReference1.GetSiteListCountRequest inValue = new ENREL.ServiceReference1.GetSiteListCountRequest();
            inValue.Body = new ENREL.ServiceReference1.GetSiteListCountRequestBody();
            ENREL.ServiceReference1.GetSiteListCountResponse retVal = ((ENREL.ServiceReference1.WebService1Soap)(this)).GetSiteListCount(inValue);
            return retVal.Body.GetSiteListCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ENREL.ServiceReference1.GetSiteListCountResponse> ENREL.ServiceReference1.WebService1Soap.GetSiteListCountAsync(ENREL.ServiceReference1.GetSiteListCountRequest request) {
            return base.Channel.GetSiteListCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<ENREL.ServiceReference1.GetSiteListCountResponse> GetSiteListCountAsync() {
            ENREL.ServiceReference1.GetSiteListCountRequest inValue = new ENREL.ServiceReference1.GetSiteListCountRequest();
            inValue.Body = new ENREL.ServiceReference1.GetSiteListCountRequestBody();
            return ((ENREL.ServiceReference1.WebService1Soap)(this)).GetSiteListCountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ENREL.ServiceReference1.recibirTramiteResponse ENREL.ServiceReference1.WebService1Soap.recibirTramite(ENREL.ServiceReference1.recibirTramiteRequest request) {
            return base.Channel.recibirTramite(request);
        }
        
        public bool recibirTramite(string id, ENREL.ServiceReference1.CatEmpresas empresa) {
            ENREL.ServiceReference1.recibirTramiteRequest inValue = new ENREL.ServiceReference1.recibirTramiteRequest();
            inValue.Body = new ENREL.ServiceReference1.recibirTramiteRequestBody();
            inValue.Body.id = id;
            inValue.Body.empresa = empresa;
            ENREL.ServiceReference1.recibirTramiteResponse retVal = ((ENREL.ServiceReference1.WebService1Soap)(this)).recibirTramite(inValue);
            return retVal.Body.recibirTramiteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ENREL.ServiceReference1.recibirTramiteResponse> ENREL.ServiceReference1.WebService1Soap.recibirTramiteAsync(ENREL.ServiceReference1.recibirTramiteRequest request) {
            return base.Channel.recibirTramiteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ENREL.ServiceReference1.recibirTramiteResponse> recibirTramiteAsync(string id, ENREL.ServiceReference1.CatEmpresas empresa) {
            ENREL.ServiceReference1.recibirTramiteRequest inValue = new ENREL.ServiceReference1.recibirTramiteRequest();
            inValue.Body = new ENREL.ServiceReference1.recibirTramiteRequestBody();
            inValue.Body.id = id;
            inValue.Body.empresa = empresa;
            return ((ENREL.ServiceReference1.WebService1Soap)(this)).recibirTramiteAsync(inValue);
        }
    }
}
