//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENREL.NotIOPCENACE {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotificacionDeInteroperabilidadRequest", Namespace="http://schemas.datacontract.org/2004/07/VUN.Middleware.Models.VUN_SENER")]
    [System.SerializableAttribute()]
    public partial class NotificacionDeInteroperabilidadRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ENREL.NotIOPCENACE.DocumentosAdjuntos DocumentosAdjuntosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ENREL.NotIOPCENACE.HeaderInteroperabilidad HeaderInteroperabilidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ENREL.NotIOPCENACE.InformacionDeNegocio InformacionDeNegocioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ENREL.NotIOPCENACE.DocumentosAdjuntos DocumentosAdjuntos {
            get {
                return this.DocumentosAdjuntosField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentosAdjuntosField, value) != true)) {
                    this.DocumentosAdjuntosField = value;
                    this.RaisePropertyChanged("DocumentosAdjuntos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ENREL.NotIOPCENACE.HeaderInteroperabilidad HeaderInteroperabilidad {
            get {
                return this.HeaderInteroperabilidadField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderInteroperabilidadField, value) != true)) {
                    this.HeaderInteroperabilidadField = value;
                    this.RaisePropertyChanged("HeaderInteroperabilidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ENREL.NotIOPCENACE.InformacionDeNegocio InformacionDeNegocio {
            get {
                return this.InformacionDeNegocioField;
            }
            set {
                if ((object.ReferenceEquals(this.InformacionDeNegocioField, value) != true)) {
                    this.InformacionDeNegocioField = value;
                    this.RaisePropertyChanged("InformacionDeNegocio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentosAdjuntos", Namespace="http://schemas.datacontract.org/2004/07/VUN.Middleware.Models.VUN_SENER")]
    [System.SerializableAttribute()]
    public partial class DocumentosAdjuntos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HeaderInteroperabilidad", Namespace="http://schemas.datacontract.org/2004/07/VUN.Middleware.Models.VUN_SENER")]
    [System.SerializableAttribute()]
    public partial class HeaderInteroperabilidad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinoNegocioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FolioPeticionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomoclaveDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdConsumidorIOPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdGlobalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdProductorIOPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrigenNegocioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinoNegocio {
            get {
                return this.DestinoNegocioField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinoNegocioField, value) != true)) {
                    this.DestinoNegocioField = value;
                    this.RaisePropertyChanged("DestinoNegocio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FolioPeticion {
            get {
                return this.FolioPeticionField;
            }
            set {
                if ((object.ReferenceEquals(this.FolioPeticionField, value) != true)) {
                    this.FolioPeticionField = value;
                    this.RaisePropertyChanged("FolioPeticion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomoclaveDestino {
            get {
                return this.HomoclaveDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.HomoclaveDestinoField, value) != true)) {
                    this.HomoclaveDestinoField = value;
                    this.RaisePropertyChanged("HomoclaveDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdConsumidorIOP {
            get {
                return this.IdConsumidorIOPField;
            }
            set {
                if ((object.ReferenceEquals(this.IdConsumidorIOPField, value) != true)) {
                    this.IdConsumidorIOPField = value;
                    this.RaisePropertyChanged("IdConsumidorIOP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdGlobal {
            get {
                return this.IdGlobalField;
            }
            set {
                if ((object.ReferenceEquals(this.IdGlobalField, value) != true)) {
                    this.IdGlobalField = value;
                    this.RaisePropertyChanged("IdGlobal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdProductorIOP {
            get {
                return this.IdProductorIOPField;
            }
            set {
                if ((object.ReferenceEquals(this.IdProductorIOPField, value) != true)) {
                    this.IdProductorIOPField = value;
                    this.RaisePropertyChanged("IdProductorIOP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identidad {
            get {
                return this.IdentidadField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentidadField, value) != true)) {
                    this.IdentidadField = value;
                    this.RaisePropertyChanged("Identidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrigenNegocio {
            get {
                return this.OrigenNegocioField;
            }
            set {
                if ((object.ReferenceEquals(this.OrigenNegocioField, value) != true)) {
                    this.OrigenNegocioField = value;
                    this.RaisePropertyChanged("OrigenNegocio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InformacionDeNegocio", Namespace="http://schemas.datacontract.org/2004/07/VUN.Middleware.Models.VUN_SENER")]
    [System.SerializableAttribute()]
    public partial class InformacionDeNegocio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ENREL.NotIOPCENACE.CamposPersonalizados CamposPersonalizadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DependenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomoclaveOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ENREL.NotIOPCENACE.CamposPersonalizados CamposPersonalizados {
            get {
                return this.CamposPersonalizadosField;
            }
            set {
                if ((object.ReferenceEquals(this.CamposPersonalizadosField, value) != true)) {
                    this.CamposPersonalizadosField = value;
                    this.RaisePropertyChanged("CamposPersonalizados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dependencia {
            get {
                return this.DependenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.DependenciaField, value) != true)) {
                    this.DependenciaField = value;
                    this.RaisePropertyChanged("Dependencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomoclaveOrigen {
            get {
                return this.HomoclaveOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.HomoclaveOrigenField, value) != true)) {
                    this.HomoclaveOrigenField = value;
                    this.RaisePropertyChanged("HomoclaveOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CamposPersonalizados", Namespace="http://schemas.datacontract.org/2004/07/VUN.Middleware.Models.VUN_SENER")]
    [System.SerializableAttribute()]
    public partial class CamposPersonalizados : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ENREL.NotIOPCENACE.Empresa EmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ENREL.NotIOPCENACE.Proyecto ProyectoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ENREL.NotIOPCENACE.RepresentanteLegal RepresentanteLegalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ENREL.NotIOPCENACE.Empresa Empresa {
            get {
                return this.EmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpresaField, value) != true)) {
                    this.EmpresaField = value;
                    this.RaisePropertyChanged("Empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ENREL.NotIOPCENACE.Proyecto Proyecto {
            get {
                return this.ProyectoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProyectoField, value) != true)) {
                    this.ProyectoField = value;
                    this.RaisePropertyChanged("Proyecto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ENREL.NotIOPCENACE.RepresentanteLegal RepresentanteLegal {
            get {
                return this.RepresentanteLegalField;
            }
            set {
                if ((object.ReferenceEquals(this.RepresentanteLegalField, value) != true)) {
                    this.RepresentanteLegalField = value;
                    this.RaisePropertyChanged("RepresentanteLegal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empresa", Namespace="http://schemas.datacontract.org/2004/07/VUN.Middleware.Models.VUN_SENER")]
    [System.SerializableAttribute()]
    public partial class Empresa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPostalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColoniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntidadFederativaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MunicipioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreComercialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroExteriorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroInteriorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoFijoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoAsentamientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoVialidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Calle {
            get {
                return this.CalleField;
            }
            set {
                if ((object.ReferenceEquals(this.CalleField, value) != true)) {
                    this.CalleField = value;
                    this.RaisePropertyChanged("Calle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPostal {
            get {
                return this.CodigoPostalField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPostalField, value) != true)) {
                    this.CodigoPostalField = value;
                    this.RaisePropertyChanged("CodigoPostal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Colonia {
            get {
                return this.ColoniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ColoniaField, value) != true)) {
                    this.ColoniaField = value;
                    this.RaisePropertyChanged("Colonia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronico {
            get {
                return this.CorreoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoElectronicoField, value) != true)) {
                    this.CorreoElectronicoField = value;
                    this.RaisePropertyChanged("CorreoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntidadFederativa {
            get {
                return this.EntidadFederativaField;
            }
            set {
                if ((object.ReferenceEquals(this.EntidadFederativaField, value) != true)) {
                    this.EntidadFederativaField = value;
                    this.RaisePropertyChanged("EntidadFederativa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lada {
            get {
                return this.LadaField;
            }
            set {
                if ((object.ReferenceEquals(this.LadaField, value) != true)) {
                    this.LadaField = value;
                    this.RaisePropertyChanged("Lada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Localidad {
            get {
                return this.LocalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalidadField, value) != true)) {
                    this.LocalidadField = value;
                    this.RaisePropertyChanged("Localidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Municipio {
            get {
                return this.MunicipioField;
            }
            set {
                if ((object.ReferenceEquals(this.MunicipioField, value) != true)) {
                    this.MunicipioField = value;
                    this.RaisePropertyChanged("Municipio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreComercial {
            get {
                return this.NombreComercialField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreComercialField, value) != true)) {
                    this.NombreComercialField = value;
                    this.RaisePropertyChanged("NombreComercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroExterior {
            get {
                return this.NumeroExteriorField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroExteriorField, value) != true)) {
                    this.NumeroExteriorField = value;
                    this.RaisePropertyChanged("NumeroExterior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroInterior {
            get {
                return this.NumeroInteriorField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroInteriorField, value) != true)) {
                    this.NumeroInteriorField = value;
                    this.RaisePropertyChanged("NumeroInterior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefonoFijo {
            get {
                return this.TelefonoFijoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoFijoField, value) != true)) {
                    this.TelefonoFijoField = value;
                    this.RaisePropertyChanged("TelefonoFijo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoAsentamiento {
            get {
                return this.TipoAsentamientoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoAsentamientoField, value) != true)) {
                    this.TipoAsentamientoField = value;
                    this.RaisePropertyChanged("TipoAsentamiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoVialidad {
            get {
                return this.TipoVialidadField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoVialidadField, value) != true)) {
                    this.TipoVialidadField = value;
                    this.RaisePropertyChanged("TipoVialidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proyecto", Namespace="http://schemas.datacontract.org/2004/07/VUN.Middleware.Models.VUN_SENER")]
    [System.SerializableAttribute()]
    public partial class Proyecto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_AvanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_CapacidadInstaladaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_CodigoPostalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_ColoniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_EntidadFederativaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_EstatusProyectoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_FactorPlantaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_FaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_GeneracionAnualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_IdGlobalMacroTramiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_IdTipoAsentamientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_IdTipoVialidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_LatitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_LocalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_LongitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_MontoInversionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_MunicipioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_NombreProyectoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_PorcentajePositivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_TecnologiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_TipoAsentamientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_TipoVialidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_UnidadesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_Avance {
            get {
                return this.P_AvanceField;
            }
            set {
                if ((object.ReferenceEquals(this.P_AvanceField, value) != true)) {
                    this.P_AvanceField = value;
                    this.RaisePropertyChanged("P_Avance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_CapacidadInstalada {
            get {
                return this.P_CapacidadInstaladaField;
            }
            set {
                if ((object.ReferenceEquals(this.P_CapacidadInstaladaField, value) != true)) {
                    this.P_CapacidadInstaladaField = value;
                    this.RaisePropertyChanged("P_CapacidadInstalada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_CodigoPostal {
            get {
                return this.P_CodigoPostalField;
            }
            set {
                if ((object.ReferenceEquals(this.P_CodigoPostalField, value) != true)) {
                    this.P_CodigoPostalField = value;
                    this.RaisePropertyChanged("P_CodigoPostal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_Colonia {
            get {
                return this.P_ColoniaField;
            }
            set {
                if ((object.ReferenceEquals(this.P_ColoniaField, value) != true)) {
                    this.P_ColoniaField = value;
                    this.RaisePropertyChanged("P_Colonia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_EntidadFederativa {
            get {
                return this.P_EntidadFederativaField;
            }
            set {
                if ((object.ReferenceEquals(this.P_EntidadFederativaField, value) != true)) {
                    this.P_EntidadFederativaField = value;
                    this.RaisePropertyChanged("P_EntidadFederativa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_EstatusProyecto {
            get {
                return this.P_EstatusProyectoField;
            }
            set {
                if ((object.ReferenceEquals(this.P_EstatusProyectoField, value) != true)) {
                    this.P_EstatusProyectoField = value;
                    this.RaisePropertyChanged("P_EstatusProyecto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_FactorPlanta {
            get {
                return this.P_FactorPlantaField;
            }
            set {
                if ((object.ReferenceEquals(this.P_FactorPlantaField, value) != true)) {
                    this.P_FactorPlantaField = value;
                    this.RaisePropertyChanged("P_FactorPlanta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_Fase {
            get {
                return this.P_FaseField;
            }
            set {
                if ((object.ReferenceEquals(this.P_FaseField, value) != true)) {
                    this.P_FaseField = value;
                    this.RaisePropertyChanged("P_Fase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_FechaRegistro {
            get {
                return this.P_FechaRegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.P_FechaRegistroField, value) != true)) {
                    this.P_FechaRegistroField = value;
                    this.RaisePropertyChanged("P_FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_GeneracionAnual {
            get {
                return this.P_GeneracionAnualField;
            }
            set {
                if ((object.ReferenceEquals(this.P_GeneracionAnualField, value) != true)) {
                    this.P_GeneracionAnualField = value;
                    this.RaisePropertyChanged("P_GeneracionAnual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_IdGlobalMacroTramite {
            get {
                return this.P_IdGlobalMacroTramiteField;
            }
            set {
                if ((object.ReferenceEquals(this.P_IdGlobalMacroTramiteField, value) != true)) {
                    this.P_IdGlobalMacroTramiteField = value;
                    this.RaisePropertyChanged("P_IdGlobalMacroTramite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_IdTipoAsentamiento {
            get {
                return this.P_IdTipoAsentamientoField;
            }
            set {
                if ((object.ReferenceEquals(this.P_IdTipoAsentamientoField, value) != true)) {
                    this.P_IdTipoAsentamientoField = value;
                    this.RaisePropertyChanged("P_IdTipoAsentamiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_IdTipoVialidad {
            get {
                return this.P_IdTipoVialidadField;
            }
            set {
                if ((object.ReferenceEquals(this.P_IdTipoVialidadField, value) != true)) {
                    this.P_IdTipoVialidadField = value;
                    this.RaisePropertyChanged("P_IdTipoVialidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_Latitud {
            get {
                return this.P_LatitudField;
            }
            set {
                if ((object.ReferenceEquals(this.P_LatitudField, value) != true)) {
                    this.P_LatitudField = value;
                    this.RaisePropertyChanged("P_Latitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_Localidad {
            get {
                return this.P_LocalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.P_LocalidadField, value) != true)) {
                    this.P_LocalidadField = value;
                    this.RaisePropertyChanged("P_Localidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_Longitud {
            get {
                return this.P_LongitudField;
            }
            set {
                if ((object.ReferenceEquals(this.P_LongitudField, value) != true)) {
                    this.P_LongitudField = value;
                    this.RaisePropertyChanged("P_Longitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_MontoInversion {
            get {
                return this.P_MontoInversionField;
            }
            set {
                if ((object.ReferenceEquals(this.P_MontoInversionField, value) != true)) {
                    this.P_MontoInversionField = value;
                    this.RaisePropertyChanged("P_MontoInversion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_Municipio {
            get {
                return this.P_MunicipioField;
            }
            set {
                if ((object.ReferenceEquals(this.P_MunicipioField, value) != true)) {
                    this.P_MunicipioField = value;
                    this.RaisePropertyChanged("P_Municipio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_NombreProyecto {
            get {
                return this.P_NombreProyectoField;
            }
            set {
                if ((object.ReferenceEquals(this.P_NombreProyectoField, value) != true)) {
                    this.P_NombreProyectoField = value;
                    this.RaisePropertyChanged("P_NombreProyecto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_PorcentajePositivo {
            get {
                return this.P_PorcentajePositivoField;
            }
            set {
                if ((object.ReferenceEquals(this.P_PorcentajePositivoField, value) != true)) {
                    this.P_PorcentajePositivoField = value;
                    this.RaisePropertyChanged("P_PorcentajePositivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_Tecnologia {
            get {
                return this.P_TecnologiaField;
            }
            set {
                if ((object.ReferenceEquals(this.P_TecnologiaField, value) != true)) {
                    this.P_TecnologiaField = value;
                    this.RaisePropertyChanged("P_Tecnologia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_TipoAsentamiento {
            get {
                return this.P_TipoAsentamientoField;
            }
            set {
                if ((object.ReferenceEquals(this.P_TipoAsentamientoField, value) != true)) {
                    this.P_TipoAsentamientoField = value;
                    this.RaisePropertyChanged("P_TipoAsentamiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_TipoVialidad {
            get {
                return this.P_TipoVialidadField;
            }
            set {
                if ((object.ReferenceEquals(this.P_TipoVialidadField, value) != true)) {
                    this.P_TipoVialidadField = value;
                    this.RaisePropertyChanged("P_TipoVialidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_Unidades {
            get {
                return this.P_UnidadesField;
            }
            set {
                if ((object.ReferenceEquals(this.P_UnidadesField, value) != true)) {
                    this.P_UnidadesField = value;
                    this.RaisePropertyChanged("P_Unidades");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RepresentanteLegal", Namespace="http://schemas.datacontract.org/2004/07/VUN.Middleware.Models.VUN_SENER")]
    [System.SerializableAttribute()]
    public partial class RepresentanteLegal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CURPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPostalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColoniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntidadFederativaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtensionTelefonicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MunicipioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroExteriorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroInteriorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegundoApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoCelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoFijoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoAsentamientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoVialidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CURP {
            get {
                return this.CURPField;
            }
            set {
                if ((object.ReferenceEquals(this.CURPField, value) != true)) {
                    this.CURPField = value;
                    this.RaisePropertyChanged("CURP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Calle {
            get {
                return this.CalleField;
            }
            set {
                if ((object.ReferenceEquals(this.CalleField, value) != true)) {
                    this.CalleField = value;
                    this.RaisePropertyChanged("Calle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPostal {
            get {
                return this.CodigoPostalField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPostalField, value) != true)) {
                    this.CodigoPostalField = value;
                    this.RaisePropertyChanged("CodigoPostal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Colonia {
            get {
                return this.ColoniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ColoniaField, value) != true)) {
                    this.ColoniaField = value;
                    this.RaisePropertyChanged("Colonia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronico {
            get {
                return this.CorreoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoElectronicoField, value) != true)) {
                    this.CorreoElectronicoField = value;
                    this.RaisePropertyChanged("CorreoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntidadFederativa {
            get {
                return this.EntidadFederativaField;
            }
            set {
                if ((object.ReferenceEquals(this.EntidadFederativaField, value) != true)) {
                    this.EntidadFederativaField = value;
                    this.RaisePropertyChanged("EntidadFederativa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtensionTelefonica {
            get {
                return this.ExtensionTelefonicaField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionTelefonicaField, value) != true)) {
                    this.ExtensionTelefonicaField = value;
                    this.RaisePropertyChanged("ExtensionTelefonica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lada {
            get {
                return this.LadaField;
            }
            set {
                if ((object.ReferenceEquals(this.LadaField, value) != true)) {
                    this.LadaField = value;
                    this.RaisePropertyChanged("Lada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Localidad {
            get {
                return this.LocalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalidadField, value) != true)) {
                    this.LocalidadField = value;
                    this.RaisePropertyChanged("Localidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Municipio {
            get {
                return this.MunicipioField;
            }
            set {
                if ((object.ReferenceEquals(this.MunicipioField, value) != true)) {
                    this.MunicipioField = value;
                    this.RaisePropertyChanged("Municipio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroExterior {
            get {
                return this.NumeroExteriorField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroExteriorField, value) != true)) {
                    this.NumeroExteriorField = value;
                    this.RaisePropertyChanged("NumeroExterior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroInterior {
            get {
                return this.NumeroInteriorField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroInteriorField, value) != true)) {
                    this.NumeroInteriorField = value;
                    this.RaisePropertyChanged("NumeroInterior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegundoApellido {
            get {
                return this.SegundoApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.SegundoApellidoField, value) != true)) {
                    this.SegundoApellidoField = value;
                    this.RaisePropertyChanged("SegundoApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefonoCelular {
            get {
                return this.TelefonoCelularField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoCelularField, value) != true)) {
                    this.TelefonoCelularField = value;
                    this.RaisePropertyChanged("TelefonoCelular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefonoFijo {
            get {
                return this.TelefonoFijoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoFijoField, value) != true)) {
                    this.TelefonoFijoField = value;
                    this.RaisePropertyChanged("TelefonoFijo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoAsentamiento {
            get {
                return this.TipoAsentamientoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoAsentamientoField, value) != true)) {
                    this.TipoAsentamientoField = value;
                    this.RaisePropertyChanged("TipoAsentamiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoVialidad {
            get {
                return this.TipoVialidadField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoVialidadField, value) != true)) {
                    this.TipoVialidadField = value;
                    this.RaisePropertyChanged("TipoVialidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotificacionDeInteroperabilidadResponse", Namespace="http://schemas.datacontract.org/2004/07/VUN.Middleware.Models.VUN_SENER")]
    [System.SerializableAttribute()]
    public partial class NotificacionDeInteroperabilidadResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ENREL.NotIOPCENACE.Client ClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ENREL.NotIOPCENACE.EstatusEntregaMensaje EstatusEntregaMensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FolioPeticionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FolioRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IssueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProtocolVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ENREL.NotIOPCENACE.Service ServiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ENREL.NotIOPCENACE.Client Client {
            get {
                return this.ClientField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientField, value) != true)) {
                    this.ClientField = value;
                    this.RaisePropertyChanged("Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ENREL.NotIOPCENACE.EstatusEntregaMensaje EstatusEntregaMensaje {
            get {
                return this.EstatusEntregaMensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.EstatusEntregaMensajeField, value) != true)) {
                    this.EstatusEntregaMensajeField = value;
                    this.RaisePropertyChanged("EstatusEntregaMensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FolioPeticion {
            get {
                return this.FolioPeticionField;
            }
            set {
                if ((object.ReferenceEquals(this.FolioPeticionField, value) != true)) {
                    this.FolioPeticionField = value;
                    this.RaisePropertyChanged("FolioPeticion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FolioRespuesta {
            get {
                return this.FolioRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.FolioRespuestaField, value) != true)) {
                    this.FolioRespuestaField = value;
                    this.RaisePropertyChanged("FolioRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Issue {
            get {
                return this.IssueField;
            }
            set {
                if ((object.ReferenceEquals(this.IssueField, value) != true)) {
                    this.IssueField = value;
                    this.RaisePropertyChanged("Issue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProtocolVersion {
            get {
                return this.ProtocolVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.ProtocolVersionField, value) != true)) {
                    this.ProtocolVersionField = value;
                    this.RaisePropertyChanged("ProtocolVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ENREL.NotIOPCENACE.Service Service {
            get {
                return this.ServiceField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceField, value) != true)) {
                    this.ServiceField = value;
                    this.RaisePropertyChanged("Service");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/VUN.Middleware.Models.VUN_SENER")]
    [System.SerializableAttribute()]
    public partial class Client : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstatusEntregaMensaje", Namespace="http://schemas.datacontract.org/2004/07/VUN.Middleware.Models.VUN_SENER")]
    [System.SerializableAttribute()]
    public partial class EstatusEntregaMensaje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Service", Namespace="http://schemas.datacontract.org/2004/07/VUN.Middleware.Models.VUN_SENER")]
    [System.SerializableAttribute()]
    public partial class Service : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NotIOPCENACE.IVunSvc")]
    public interface IVunSvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVunSvc/Ping", ReplyAction="http://tempuri.org/IVunSvc/PingResponse")]
        string Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVunSvc/Ping", ReplyAction="http://tempuri.org/IVunSvc/PingResponse")]
        System.Threading.Tasks.Task<string> PingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVunSvc/NotificacionDeInteroperabilidadRequest", ReplyAction="http://tempuri.org/IVunSvc/NotificacionDeInteroperabilidadRequestResponse")]
        ENREL.NotIOPCENACE.NotificacionDeInteroperabilidadResponse NotificacionDeInteroperabilidadRequest(ENREL.NotIOPCENACE.NotificacionDeInteroperabilidadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVunSvc/NotificacionDeInteroperabilidadRequest", ReplyAction="http://tempuri.org/IVunSvc/NotificacionDeInteroperabilidadRequestResponse")]
        System.Threading.Tasks.Task<ENREL.NotIOPCENACE.NotificacionDeInteroperabilidadResponse> NotificacionDeInteroperabilidadRequestAsync(ENREL.NotIOPCENACE.NotificacionDeInteroperabilidadRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVunSvcChannel : ENREL.NotIOPCENACE.IVunSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VunSvcClient : System.ServiceModel.ClientBase<ENREL.NotIOPCENACE.IVunSvc>, ENREL.NotIOPCENACE.IVunSvc {
        
        public VunSvcClient() {
        }
        
        public VunSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VunSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VunSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VunSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Ping() {
            return base.Channel.Ping();
        }
        
        public System.Threading.Tasks.Task<string> PingAsync() {
            return base.Channel.PingAsync();
        }
        
        public ENREL.NotIOPCENACE.NotificacionDeInteroperabilidadResponse NotificacionDeInteroperabilidadRequest(ENREL.NotIOPCENACE.NotificacionDeInteroperabilidadRequest request) {
            return base.Channel.NotificacionDeInteroperabilidadRequest(request);
        }
        
        public System.Threading.Tasks.Task<ENREL.NotIOPCENACE.NotificacionDeInteroperabilidadResponse> NotificacionDeInteroperabilidadRequestAsync(ENREL.NotIOPCENACE.NotificacionDeInteroperabilidadRequest request) {
            return base.Channel.NotificacionDeInteroperabilidadRequestAsync(request);
        }
    }
}
