//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENREL.WSBPM_Nivel0 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xmlns.oracle.com/bpmn/bpmnProcess/ProcessNivel0", ConfigurationName="WSBPM_Nivel0.ProcessNivel0PortType")]
    public interface ProcessNivel0PortType {
        
        // CODEGEN: Generating message contract since element name Idproyecto from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="InicioNivel0")]
        void InicioNivel0(ENREL.WSBPM_Nivel0.InicioNivel0 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="InicioNivel0")]
        System.Threading.Tasks.Task InicioNivel0Async(ENREL.WSBPM_Nivel0.InicioNivel0 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InicioNivel0 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InicioNivel0", Namespace="http://xmlns.oracle.com/bpmn/bpmnProcess/ProcessNivel0", Order=0)]
        public ENREL.WSBPM_Nivel0.InicioNivel0Body Body;
        
        public InicioNivel0() {
        }
        
        public InicioNivel0(ENREL.WSBPM_Nivel0.InicioNivel0Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InicioNivel0Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Idproyecto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Idtecnologia;
        
        public InicioNivel0Body() {
        }
        
        public InicioNivel0Body(string Idproyecto, string Idtecnologia) {
            this.Idproyecto = Idproyecto;
            this.Idtecnologia = Idtecnologia;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProcessNivel0PortTypeChannel : ENREL.WSBPM_Nivel0.ProcessNivel0PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProcessNivel0PortTypeClient : System.ServiceModel.ClientBase<ENREL.WSBPM_Nivel0.ProcessNivel0PortType>, ENREL.WSBPM_Nivel0.ProcessNivel0PortType {
        
        public ProcessNivel0PortTypeClient() {
        }
        
        public ProcessNivel0PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProcessNivel0PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessNivel0PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessNivel0PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ENREL.WSBPM_Nivel0.ProcessNivel0PortType.InicioNivel0(ENREL.WSBPM_Nivel0.InicioNivel0 request) {
            base.Channel.InicioNivel0(request);
        }
        
        public void InicioNivel0(string Idproyecto, string Idtecnologia) {
            ENREL.WSBPM_Nivel0.InicioNivel0 inValue = new ENREL.WSBPM_Nivel0.InicioNivel0();
            inValue.Body = new ENREL.WSBPM_Nivel0.InicioNivel0Body();
            inValue.Body.Idproyecto = Idproyecto;
            inValue.Body.Idtecnologia = Idtecnologia;
            ((ENREL.WSBPM_Nivel0.ProcessNivel0PortType)(this)).InicioNivel0(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task ENREL.WSBPM_Nivel0.ProcessNivel0PortType.InicioNivel0Async(ENREL.WSBPM_Nivel0.InicioNivel0 request) {
            return base.Channel.InicioNivel0Async(request);
        }
        
        public System.Threading.Tasks.Task InicioNivel0Async(string Idproyecto, string Idtecnologia) {
            ENREL.WSBPM_Nivel0.InicioNivel0 inValue = new ENREL.WSBPM_Nivel0.InicioNivel0();
            inValue.Body = new ENREL.WSBPM_Nivel0.InicioNivel0Body();
            inValue.Body.Idproyecto = Idproyecto;
            inValue.Body.Idtecnologia = Idtecnologia;
            return ((ENREL.WSBPM_Nivel0.ProcessNivel0PortType)(this)).InicioNivel0Async(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xmlns.oracle.com/bpmn/bpmnProcess/ProcessNivel0", ConfigurationName="WSBPM_Nivel0.ProcessNivel0PortTypeCallBack")]
    public interface ProcessNivel0PortTypeCallBack {
        
        // CODEGEN: Generating message contract since the wrapper name (FinNivel0Response) of message FinNivel0 does not match the default value (FinNivel0)
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="FinNivel0")]
        void FinNivel0(ENREL.WSBPM_Nivel0.FinNivel0 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="FinNivel0")]
        System.Threading.Tasks.Task FinNivel0Async(ENREL.WSBPM_Nivel0.FinNivel0 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FinNivel0Response", WrapperNamespace="http://xmlns.oracle.com/bpmn/bpmnProcess/ProcessNivel0", IsWrapped=true)]
    public partial class FinNivel0 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Resultado;
        
        public FinNivel0() {
        }
        
        public FinNivel0(string Resultado) {
            this.Resultado = Resultado;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProcessNivel0PortTypeCallBackChannel : ENREL.WSBPM_Nivel0.ProcessNivel0PortTypeCallBack, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProcessNivel0PortTypeCallBackClient : System.ServiceModel.ClientBase<ENREL.WSBPM_Nivel0.ProcessNivel0PortTypeCallBack>, ENREL.WSBPM_Nivel0.ProcessNivel0PortTypeCallBack {
        
        public ProcessNivel0PortTypeCallBackClient() {
        }
        
        public ProcessNivel0PortTypeCallBackClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProcessNivel0PortTypeCallBackClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessNivel0PortTypeCallBackClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessNivel0PortTypeCallBackClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ENREL.WSBPM_Nivel0.ProcessNivel0PortTypeCallBack.FinNivel0(ENREL.WSBPM_Nivel0.FinNivel0 request) {
            base.Channel.FinNivel0(request);
        }
        
        public void FinNivel0(string Resultado) {
            ENREL.WSBPM_Nivel0.FinNivel0 inValue = new ENREL.WSBPM_Nivel0.FinNivel0();
            inValue.Resultado = Resultado;
            ((ENREL.WSBPM_Nivel0.ProcessNivel0PortTypeCallBack)(this)).FinNivel0(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task ENREL.WSBPM_Nivel0.ProcessNivel0PortTypeCallBack.FinNivel0Async(ENREL.WSBPM_Nivel0.FinNivel0 request) {
            return base.Channel.FinNivel0Async(request);
        }
        
        public System.Threading.Tasks.Task FinNivel0Async(string Resultado) {
            ENREL.WSBPM_Nivel0.FinNivel0 inValue = new ENREL.WSBPM_Nivel0.FinNivel0();
            inValue.Resultado = Resultado;
            return ((ENREL.WSBPM_Nivel0.ProcessNivel0PortTypeCallBack)(this)).FinNivel0Async(inValue);
        }
    }
}
